In [11]:
import pandas as pd

In [19]:
pd.read_csv(r'E:\Ankita_iNeuron\class_practice\MLDL\Python\sample-csv\contacts.csv')

,id,location_id,organization_id,service_id,name,title,email,department
0,1,1.0,NaN,NaN,Susan Houston,Director of Older Adult Services,NaN,NaN
1,2,1.0,NaN,NaN,Christina Gonzalez,Center Director,NaN,NaN
2,3,2.0,NaN,NaN,Brenda Brown,"Director, Second Career Services",NaN,NaN
3,4,3.0,NaN,NaN,"Howard Lader, LCSW","Manager, Senior Peer Counseling",NaN,NaN
4,5,4.0,NaN,NaN,Kimberly Pesavento,Director of Visitation,NaN,NaN
5,6,5.0,NaN,NaN,Joe Bloom,Financial Empowerment Programs Program Director,NaN,NaN
6,7,6.0,NaN,NaN,Peter Olson,Little House Director,NaN,NaN
7,8,6.0,NaN,NaN,Bart Charlow,"Executive Director, Peninsula Volunteers",NaN,NaN
8,9,7.0,NaN,NaN,Bart Charlow,"Executive Director, Peninsula Volunteers",NaN,NaN
9,10,7.0,NaN,NaN,Barbara Kalt,Director,NaN,NaN
10,11,8.0,NaN,NaN,Marilyn Baker-Venturini,Director,NaN,NaN
11,12,8.0,NaN,NaN,Graciela Hernandez,Assistant Manager,NaN,NaN
12,13,8.0,NaN,NaN,Julie Avelino,Assessment Specialist,NaN,NaN
13,14,9.0,NaN,NaN,Dave Genesy,Library Director,NaN,NaN
14,15,9.0,NaN,NaN,Maria Kramer,Library Divisions Manager,NaN,NaN
15,16,10.0,NaN,NaN,Dave Genesy,Library Director,NaN,NaN
16,17,10.0,NaN,NaN,Maria Kramer,Library Division Manager,NaN,NaN
17,18,11.0,NaN,NaN,Dave Genesy,Library Director,NaN,NaN
18,19,11.0,NaN,NaN,Elizabeth Meeks,Branch Manager,NaN,NaN
19,20,12.0,NaN,NaN,Kathy Endaya,Director,NaN,NaN
20,21,13.0,NaN,NaN,Dave Genesy,Library Director,NaN,NaN
21,22,14.0,NaN,NaN,Andres Espinoza,"Captain, Commanding Officer",NaN,NaN
22,23,15.0,NaN,NaN,Jack Phillips,Administrator,NaN,NaN
23,24,16.0,NaN,NaN,James Lee,Commanding Officer,NaN,NaN
24,25,17.0,NaN,NaN,Kenneth Gibson,Major,NaN,NaN
25,26,18.0,NaN,NaN,Sharon Petersen,Administrator,NaN,NaN
26,27,19.0,NaN,NaN,Sharon Petersen,Administrator,NaN,NaN
27,28,21.0,NaN,NaN,Moncef,NaN,NaN,Office of Innovation
28,29,22.0,NaN,NaN,Suzanne Badenhoop,Board President,suzanne@example.com,Referrals
29,32,NaN,8.0,NaN,Elizabeth Feeney,CEO,e.feeney@foobar.org,Operations
30,36,NaN,NaN,22.0,Joe Smith,CalFresh Specialist,john.smith@example.org,CalFresh Applications